---

ignore_list:
  - ^\./\.git/.*
  - ^\./\.vagrant/.*
  - ^\./misc/.*
  - ^\./bin/.*
  - ^\./lib/.*
  - ^\./misc/.*
  - ^\./prompts/.*
  - ^\./LICENSE
  - ^\./Makefile
  - .*\.svg$

output_file_path: null

header_prompt_file_path: null

footer_prompt_file_path: null

#
