---

ignore_list:
  - ^\.git/.*
  - ^\.vagrant/.*
  - ^misc/.*
  - ^bin/.*
  - ^lib/.*
  - ^misc/.*
  - ^prompts/.*
  - ^LICENSE
  - ^Makefile
  - .*\.svg$

output_path: null

prompt:
  header_path: null
  footer_path: null
  template_path: misc/templates/default.j2
#
