---

ignore_list:
  - ^\./.git/
  - ^\./misc/.*
  - ^\./bin
  - ^\./lib
  - ^\./misc
  - LICENSE
  - prompts
  - Makefile

output_path: null

prompt:
  header_path: null
  footer_path: prompts/footer.txt

#
